### ISSUE TITLE
Both 1.3.0 client and server downloads through FTB launcher do not work.

### ISSUE THREAD

**Issue by Ratomas** [FTBTeam/FTB-Omnia#65]
Everytime I update my server and client to 1.3.0 neither will start up. The client just says check you configuration and the server just gets stuck in a startup loop.

**Comment by ghost** [comment]
This is the same issue I'm having. There is an error in the install of 1.3.0. In my issue, they said they fixed it but it may take 30 minutes to work because of caching although I'm still having the issue. I imagine the serverside issue is the same thing although I use creeper host and they were able to fix mine.

**Comment by kylania** [comment]
I just updated 1 hour after the last report and I'm getting the same issue.

Deleted everything, fresh install of both the FTB launcher and Omnia and now it's erroring out on the initial install of the Omnia pack.

INFO: FTB Omnia 6 50
May 07, 2020 9:08:46 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Preparing instance folder for C:\FTBA\instances\f03977b4-2543-4e37-9fac-fe359bae021c
May 07, 2020 9:08:46 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: Attempting to download https://apps.modpacks.ch/versions/net/minecraftforge/forge/1.15.2-31.1.77/forge-1.15.2-31.1.77-installer.jar
May 07, 2020 9:10:04 PM net.creeperhost.creeperlauncher.CreeperLogger info
INFO: closed null with exit code 1001 additional info: 

Forge Installer seems to be giving a 404 error at that above URL.

**Comment by HalJordan** [comment]
I'm showing this in the error log here as well. I checked that url and it's a 404.

```
INFO: Attempting to download https://apps.modpacks.ch/versions/net/minecraftforge/forge/1.15.2-31.1.77/forge-1.15.2-31.1.77-installer.jar
java.util.concurrent.CompletionException: java.nio.file.FileSystemNotFoundException: /home/hal_j/.games/FTB/instances/1b4c1eb0-b66c-4950-9169-127f9e5e0a5b/installer.jar
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1739)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.nio.file.FileSystemNotFoundException: /home/hal_j/.games/FTB/instances/1b4c1eb0-b66c-4950-9169-127f9e5e0a5b/installer.jar
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:116)
        at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:136)
        at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:406)
        at net.creeperhost.creeperlauncher.util.FileUtils.fileFromZip(FileUtils.java:74)
        at net.creeperhost.creeperlauncher.util.ForgeUtils.extractJson(ForgeUtils.java:173)
        at net.creeperhost.creeperlauncher.minecraft.modloader.forge.ForgeInstallerModLoader.install(ForgeInstallerModLoader.java:43)
        at net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask.installModLoaders(FTBModPackInstallerTask.java:536)
        at net.creeperhost.creeperlauncher.install.tasks.FTBModPackInstallerTask.lambda$execute$0(FTBModPackInstallerTask.java:97)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
        ... 6 more
```

This looks like a problem with forge not the installer, as that page exists: https://apps.modpacks.ch/versions/net/minecraftforge/forge/1.15.2-31.1.77/

There's even a link for that installer, it's just a dead link.

**Comment by Sunekaer** [comment]
Should be resolved now

**Comment by Based199** [comment]
Can confirm, just started working for me.
